[package]
name = "jogo_de_adivinhacao"
version = "0.1.0"
edition = "2021"
author = "Mateus Felipe Gonçalves <mateusfelipefg77@gmail.com>"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
